### ISSUE TITLE
"Cases per 1M" returns 0 for all countries

### ISSUE THREAD

**Issue by James103** [Draylar/covid-dashboard#4]
For some reason, the values of "Cases per 1M" return 0 for all countries. This is most likely because the country's population is not fetched, causing it to return values of either 0 or Infinity behind the scenes, which both show up as 0 on the front end.

This is hardcoded here:
https://github.com/Draylar/covid-dashboard/blob/ea6904d9c46e184995e7bc7b82cdeccd28d2ba1b/script/main.js#L79

**Comment by Draylar** [comment]
Wasn't implemented because I couldn't find a way to get population count per country. Now that I look again, disease.sh's [/v3/covid-19/countries](https://corona.lmao.ninja/v3/covid-19/countries) endpoint (which I am not currently using; covid data was outdated) seems to provide population information. I'll use that to calculate cases per 1M.

**Comment by Draylar** [comment]
Fixed in 6117206e1580f1a43529d6de66335eb32e039be6
